### get all persons
GET http://localhost:3001/api/persons

### get a single person
GET http://localhost:3001/api/persons/6272e2cc04036422d99992bd

### add a single person (valid - one part), local post.rest for valid tests
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Joe Mama",
  "number": "12345678"
}

### update a single person (modify number of first person)
PUT http://localhost:3001/api/persons/6272e289622e666e9c8954a0
Content-Type: application/json

{
  "name": "Ana~~",
  "number": "12-345678"
}

### update a single person (modify number of first person)
PUT http://localhost:3001/api/persons/6272e289622e666e9c8954a0
Content-Type: application/json

{
  "name": "An",
  "number": "12-345678999"
}

### invalid update - invalid id
PUT http://localhost:3001/api/persons/123
Content-Type: application/json

{
  "name":"Kool aid man - I should not be added",
  "number":"12-345678"
}

### invalid update (no number/no name) no name
PUT http://localhost:3001/api/persons/6272e289622e666e9c8954a0
Content-Type: application/json

# {
#   "number": "888-888"
# }

{
  "name": "Ainaa~"
}

### delete a single person (try last person)
DELETE http://localhost:3001/api/persons/6272e289622e666e9c8954a0

### other
GET http://localhost:3001/info


